<?php
/**
 * Footer template part.
 *
 * 🚫🚫🚫
 * DO NOT EDIT THIS FILE WHILE INSIDE THE PLUGIN! Changes You make will be lost when a new version
 * of the AMP plugin is released. You need to copy this file out of the plugin and put it into your
 * custom theme, for example. To learn about how to customize these Reader-mode AMP templates, please
 * see: https://amp-wp.org/documentation/how-the-plugin-works/classic-templates/
 * 🚫🚫🚫
 *
 * @package AMP
 */

/**
 * Context.
 *
 * @var AMP_Post_Template $this
 */
?>
<footer class="amp-wp-footer">
	<div>
		<img src="/wp-content/uploads/2018/02/cropped-ana-1.png">
		<h2>PT. SAHABAT ANA GRUP</h2>
		<div style="line-height: normal;padding: 0px;">
			Pusat material besi &amp; baja<br>Harga partai dan eceran.
		</div>
		<br>
		<h3 style="margin: 0px;">
			Contact Info
		</h3>
		<img src="/apip/email.png" style="height: 20px;float: left;margin-right: 10px;margin-top: 3px;">
		<a class="apip_footer" href="mailto:cs@jualbesi.com">cs@jualbesi.com</a>

		<img src="/apip/email.png" style="height: 20px;float: left;margin-right: 10px;margin-top: 3px;">
		<a class="apip_footer" href="mailto:sahabatanagrup@gmail.com">sahabatanagrup@gmail.com</a>

		<img src="/apip/phone-call.png" style="height: 20px;float: left;margin-right: 10px;margin-top: 3px;">
		<a class="apip_footer" href="tel:03199160994">031 9916-0994</a>

		<img src="/apip/phone-call.png" style="height: 20px;float: left;margin-right: 10px;margin-top: 3px;">
		<a class="apip_footer" href="tel:08113666411">0811-3-666-411</a>

		<img src="/apip/pin.png" style="height: 20px;float: left;margin-right: 10px;margin-top: 3px;">
		<a class="apip_footer" href="https://www.google.co.id/maps/place/PT.+Sahabat+Ana+Grup+(Pusat+besi+hollow+di+surabaya)/@-7.2441489,112.6282674,17z/data=!3m1!4b1!4m5!3m4!1s0x2dd7fbfc7e2b6e1f:0xb5f944df349aa28b!8m2!3d-7.2441478!4d112.6304524">
	  	Jl. DK Jerawat No.31 Surabaya
	  </a>

		<br>
		<a href="#top" class="back-to-top"><?php esc_html_e( 'Back to top', 'amp' ); ?></a>
		<a href="https://api.whatsapp.com/send?phone=628113666411&text=Halo%20Sahabat%20Ana.."><div class="wa_tombol"></div></a>

	</div>
</footer>
