<!-- part 1 -->
<?php
	/**
	 * Single view template.
	 *
	 * 🚫🚫🚫
	 * DO NOT EDIT THIS FILE WHILE INSIDE THE PLUGIN! Changes You make will be lost when a new version
	 * of the AMP plugin is released. You need to copy this file out of the plugin and put it into your
	 * custom theme, for example. To learn about how to customize these Reader-mode AMP templates, please
	 * see: https://amp-wp.org/documentation/how-the-plugin-works/classic-templates/
	 * 🚫🚫🚫
	 *
	 * @package AMP
	 */

	/**
	 * Context.
	 *
	 * @var AMP_Post_Template $this
	 */

	$this->load_parts( [ 'html-start' ] );
?>
<!-- part 1 end -->


<!-- part 2 -->
<?php $this->load_parts( [ 'header' ] ); ?>
<!-- part 2 end -->


<!-- part 3 -->
<article class="amp-wp-article">
	<div>
		<amp-sidebar id="sidebar" class="sample-sidebar" layout="nodisplay" side="right">
		  <h1>Menu</h1>
			<li class="apip_li1"><a class="apip_li2" href="/">Home</a></li>
			<li class="apip_li1"><a class="apip_li2" href="/produk/">Produk</a></li>
			<li class="apip_li1"><a class="apip_li2" href="/about-us/">About</a></li>
			<li class="apip_li1"><a class="apip_li2" href="/contact-us/">Contact</a></li>
			<li class="apip_li1"><a class="apip_li2" href="/akun-saya/">Akun</a></li>
			<div class="apip_sidebar_footer1">
				<div class="apip_sidebar_footer4">

				</div>
				<div class="apip_sidebar_footer2">
					PT SAHABAT ANA GRUP
				</div>
				<div class="apip_sidebar_footer3">
					Pusat material besi & baja<br>Harga partai dan eceran.
				</div>
			</div>
		</amp-sidebar>
	</div>

	<header class="amp-wp-article-header">
		<h1 class="amp-wp-title"><?php echo $this->get( 'post_title' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></h1>
		<?php
		/**
		 * Filters the template parts loaded in the header area of the AMP legacy post template.
		 *
		 * @since 0.4
		 * @param string[] Templates to load.
		 */
		$this->load_parts( apply_filters( 'amp_post_article_header_meta', [ 'meta-author', 'meta-time' ] ) );
		?>
	</header>

	<?php $this->load_parts( [ 'featured-image' ] ); ?>



	<!-- Apip Code -->
	<div id="apip_amp1">
		<?php
			$link = $_SERVER['REQUEST_URI'];
			if (strpos($link, 'produk') !== false) {
		    echo do_shortcode( '[apip_amp]' );
			}
		?>
	</div>
	<!-- Apip Code End -->



	<div class="amp-wp-article-content">
		<?php echo $this->get( 'post_amp_content' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
	</div>


	<?php
		if ( ! defined( 'ABSPATH' ) ) {
			exit; // Exit if accessed directly.
		}

		global $post;

		$short_description = apply_filters( 'woocommerce_short_description', $post->post_excerpt );


		if ( ! $short_description ) {
			return;
		}

	?>
	<div class="woocommerce-product-details__short-description">
		<?php //echo $short_description; // echo do_shortcode( '[ayi]' );  ?>
		<?php //echo do_shortcode( '[apip_amp]' );?>

	</div>

	<footer class="amp-wp-article-footer">
		<?php
		/**
		 * Filters the template parts to load in the footer area of the AMP legacy post template.
		 *
		 * @since 0.4
		 * @param string[] Templates to load.
		 */
		$this->load_parts( apply_filters( 'amp_post_article_footer_meta', [ 'meta-taxonomy', 'meta-comments-link' ] ) );
		?>
	</footer>
</article>
<!-- part 3 end -->


<!-- part 4 -->
<?php
	$this->load_parts( [ 'footer' ] );
	// load_parts( [ 'footer' ] );

?>
<!-- part 4 end-->


<!-- part 5 -->
<?php
$this->load_parts( [ 'html-end' ] );
